baseURL = "https://swapnilogale.github.io/"
languageCode = "en-us"
title = "Swapnil Portfolio"
theme = "hugo-resume"
customCSS = ["swaptheme.css"]
publishDir = "swapnilogale.github.io"

[params]
    firstName = "Swapnil"
    lastName = "Ogale"
    address = "Melbourne, Australia"
    phone = "61-422593837"
    contactNote = "Technical Writer" #used in QR code only
    profileImage = "img/SOHead.png"
    email = "swapnilogale@netscape.net"
    description = "Technical Writer with over 16 years of experience (including remote) with demonstrated experience in content design, information architecture, product content, and leading/managing documentation projects."
    favicon = "images/favicon.ico"

    # what sections to display.  Setting to false disables navigation and section.
    showSkills = true
    showProjects = true
    showOpenSource = true
    showPublications = true
    showExperience = true
    showEducation = true

    # do you want to show git hash on page footer and link to repo? Add commit URl for repo here.
    gitCommitPrefix = "https://github.com/YOURNAME/REPONAME/commit/"


[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/swapnilogale/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/swapnilogale/"

[[params.handles]]
    name = "Twitter"
    link = "https://twitter.com/swapnilogale"